import pdb

from models.doctor import Doctor
from models.vigilante import Vigilante
from models.patient import Patient

import repositories.doctor_repository as doctor_repository
import repositories.vigilante_repository as vigilante_repository
import repositories.patient_repository as patient_repository

patient_repository.delete_all()
vigilante_repository.delete_all()
doctor_repository.delete_all()

notes1 = " MY MOST CHALLENGING PATIENT AT ARKHAM. THE JOKER'S DERANGEMENT DEFIES EASY CLASS. HIS RAPIDLY CHANGING MOOD SWINGS HINT AT BORDERLINE PERSONALITY DISORDER, BUT HE HAS NO TRACE OF ASSOCIATED IDENTITY PROBLEMS. HE ALSO DISPLAYS SIGNS OF DEEP NARCISSISM, BUT NONETHELESS HE HAS A WELL-DEVELOPED SENSE OF OTHERS, AS HIS ABILITY TO MANIPULATE EVERYONE FROM ORDERLIES TO DOCTORS IN ARKHAM IS EXTRAORDINARILY WELL-DEVELOPED; HE ALSO SHOWS ALL THE SIGNS OF A HIGHLY FUNCTIONING SUFFERER OF ANTISOCIAL PERSONALITY. AT TIMES I ACTUALLY WONDER IF HE IS ACTUALLY INSANE AT ALL. ADDITIONAL NOTES: HIS CRIMINAL RECORD MAKES CLEAR THAT HE IS AN UNREPENTANT HOMICIDAL MANIAC. HE IS EXTREMELY MANIPULATIVE; THE FILE DETAILING HARLEY QUINN'S ASSOCIATIONS WITH HIM IS FASCINATING READING. IT'S UNFORTUNATE I WAS NOT ON STAFF AT THE TIME TO WITNESS HIS SEDUCTION OF HER FIRSTHAND. HIS PAST IS UNKNOWN, AND HIS ANSWERS TO ME ABOUT IT ARE WILDLY INCONSISTENT AND FREQUENTLY FANTASTICAL."

notes2 = "POSSIBLY ONE OF MY GREATEST SUCCESSES HERE AT THE ASYLUM. DESPITE HIS TENDENCY FOR EXTENSIVE ROLE-PLAY (ODDLY COMMON AMONG GOTHAM CITY'S CRIMINALS), IT'S UNCLEAR TO ME WHY DR. CRANE WAS EVER CONSIDERED INSANE. IN OUR LONG DISCUSSIONS, I'VE BEEN IMPRESSED WITH HIS GENIUS FOR PSYCHOLOGY AND BIOCHEMISTRY, AND I FULLY BELIEVE THAT IF PRESENTED WITH A STOCK OF HIS FEAR-INDUCING GAS, HE WOULD FEEL NO COMPULSION TO USE IT. HE SEEMS TO HAVE ENTIRELY TURNED AWAY FROM HIS FORMER LIFE OF CRIME AS THE SCARECROW. ADDITIONAL NOTES: HE'S VALIANTLY BATTLED A HISTORY OF ANXIETY DISORDER, DUE TO A DIFFICULT CHILDHOOD AND ADULTHOOD TRAUMA, THROUGH AN INTENSE STUDY OF PSYCHOLOGY AND THE CAUSES OF FEAR. I'VE COME TO BELIEVE THAT THE ACCUSATIONS THAT HE EXPERIMENTED ON HUMAN SUBJECTS ARE WILDLY EXAGGERATED."

notes3 = "PUSHED INTO SCHIZOTYPAL BEHAVIOR BY AN INFERIORITY COMPLEX. COBBLEPOT'S SPECIFIC ECCENTRICITIES REVOLVE AROUND AN OBSESSION WITH ORNITHOLOGY AND INTENSE IDEATION BASED AROUND UMBRELLAS. EVEN WITHIN THE CONFINES OF THE ASYLUM, HE HAS MANAGED TO CREATE WORKING UMBRELLAS WITH 'TRICK' FEATURES. MALTREATMENT BY OTHER INMATES AND PROBINGS INTO POSSIBLE SOURCES FOR HIS INSECURITIES ALWAYS TRIGGER INTENSE OVERCOMPENSATION ON HIS PART, IN THE FORM OF RANTINGS ABOUT HIS BUSINESS ACUMEN AND MISUNDERSTOOD INTELLIGENCE. ADDITIONAL NOTES: HIS OFF-PUTTING, ANTISOCIAL BEHAVIOR IS FREQUENTLY AT ODDS WITH HIS NEED TO BE VALUED AND ADMIRED. HE IS COMPULSIVE ABOUT HIS SARTORIAL APPEARANCE, WHICH CONFLICTS WITH HIS AVOIDANCE AND DENIAL OF HIS PHYSICAL SHORTCOMINGS."

notes4 = "AS WITH MANY OF THE INMATES HERE, NIGMA HAS AN ABNORMALLY HIGH IQ, BUT THIS IS TEMPERED BY HIS INTENSE NARCISSISM AND HIS OBSESSIVE-COMPULSIVE NEED TO DEVISE AND DISSEMINATE HIS (SURPRISINGLY INGENIOUS) RIDDLES AND PUZZLES. IF THERE WERE A WAY TO BREAK HIS HISTRIONIC BEHAVIOR AND ITS UNDERLYING EGO-MANIACAL CAUSES, HE COULD BE CURED. IT IS A PUZZLE ONLY I AM TRULY CAPABLE OF SOLVING. ADDITIONAL NOTES: I CANNOT HELP BUT ADMIRE THE COMPLEXITY, AND YET APPARENT SIMPLICITY, OF THE MANY CONUNDRUMS AND RIDDLES NIGMA REGULARLY PRESENTED ME WITH IN HIS TREATMENT SESSIONS. OFTEN I FIND MYSELF WORKING THROUGH THEM IN MY (INFREQUENT) FREE TIME. HIS OBSESSION WITH DISPLAYING HIS OWN INTELLIGENCE IS THE CENTRAL TRIGGER OF HIS MANY PERSONALITY DISORDERS."

notes5 = "YET ANOTHER PATIENT WHOSE TREATMENT IS COMPLICATED BY A BIZARRE MEDICAL CONDITION, ISLEY HAS A MODIFIED GENETIC CODE THAT INCORPORATES PLANT DNA AND RENDERS HER PHYSICALLY TOXIC TO OTHERS. SHE IS ESSENTIALLY DEEPLY ANTISOCIAL, BELIEVING HERSELF TO BE NOT ONLY INHUMAN BUT SUPERIOR TO OTHERS; THIS DIAGNOSIS IS TIED INTO HER HYPERSEXUALITY, WHICH TAKES THE FORM OF A CONSTANT ATTEMPT TO SEDUCE OTHERS TO DO HER BIDDING. SHE ALSO DISPLAYS A NARCISSISTIC BELIEF IN HER ROLE AS THE PROTECTOR OF THE ENTIRE NATURAL WORLD. ADDITIONAL NOTES: ODDLY, ISLEY IS ANOTHER FORMER DOCTOR WHO IS NOW AN INMATE (LIKE HARLEY QUINN). SHE SEEMS RESENTFUL DURING OUR TREATMENT SESSIONS; I BELIEVE THE FACT I'M A WOMAN FRUSTRATES HER EROTOMANIA. SHE DESPERATELY BELIEVES THAT ALL MALE RESIDENTS OF ARKHAM ARE AT LEAST PARTLY IN LOVE WITH HER. I'VE BEEN LOOKING THROUGH HER OLD RESEARCH PAPERS, MANY OF WHICH WERE NEVER PUBLISHED. THERE IS SOME FASCINATING WORK THERE..."

notes6 = "WHILE HIS BIZARRE ABILITY TO SHAPE-CHANGE OPENS HIM UP TO THE OBVIOUS, IF CONTROVERSIAL, DIAGNOSIS OF MULTIPLE PERSONALITY DISORDER, KARLO SEEMS INSTEAD TO BE SUFFERING FROM BORDERLINE PERSONALITY DISORDER, WITH A SPECIAL EMPHASIS ON IDENTITY DISTURBANCE. HE IS DIFFICULT TO PIN DOWN ON ANY SUBJECT, AND DEFENDS HIS WILD CHANGES IN AFFECT AS EVIDENCE OF HIS DRAMATIC ABILITIES, WHICH HE CONSIDERS TO BE WILDLY UNDERRATED. RARELY DOES HE TAKE HIS OWN SHAPE, BUT FREQUENTLY MIMICS ME WHEN I ATTEMPT TO INTERVIEW HIM. ADDITIONAL NOTES: HIS IDENTITY IS AT RISK OF SPLINTERING, DUE TO THE GROWING FREQUENCY OF HIS ADOPTING THE IDENTITIES OF OTHERS TO THE EXCLUSION OF TAKING ON HIS OWN. I FIND HIS IMITATION OF ME TO BE ESPECIALLY UNFLATTERING; I AM MOST CERTAINLY NOT THE BITTER, CALCULATING ACADEMIC HE ATTEMPTS TO PORTRAY ME AS."

notes7 = "A BIZARRE SCHIZOTYPAL, DENT SHOWS INTENSE IDEATION FOCUSED ON THE CONCEPT OF DUALISM. THIS ARISES OUT OF HIS UNIQUE FACIAL DISFIGUREMENT (HALF OF HIS FACE HAS BEEN SCARRED BY ACID) AS SHOWN BY ITS EMERGENCE CONCURRENT WITH THE INCIDENT THAT SCARRED HIM. HE HAS NO PRIOR HISTORY OF PSYCHOPATHIC BEHAVIOR, BUT SINCE HIS DISFIGUREMENT HE HAS CONTINUALLY CREATED SITUATIONS BASED ON POSITIVE AND NEGATIVE OUTCOMES WITH CHANCE AS THE DECIDING FACTOR. HE ACCEPTS NO RESPONSIBILITY FOR THE SOCIOPATHIC, DESTRUCTIVE OUTCOMES THAT RESULT APPROXIMATELY 50% OF THE TIME. ADDITIONAL NOTES: DENT'S IDEATION AROUND DUALISM EXTENDS TO HIS CLOTHING, HIS ENVIRONMENTS, AND THE CENTRAL TOKEN OF HIS PSYCHOLOGICAL MAKE-UP, HIS HALF-SCARRED SILVER DOLLAR. HE BECOMES CATATONIC IF IT IS REMOVED FROM HIM. PERHAPS I SHOULD BE UNSURPRISED THAT ONLY HALF OF OUR TREATMENT SESSIONS ARE PRODUCTIVE. THE OTHER HALF ARE CHARACTERIZED BY ENDLESS, POINTLESS WORD GAMES REVOLVING AROUND CHANCE AND FATE."

notes8 = "JONES WAS BORN WITH A RARE MUTATION THAT CREATED A SERIES OF PHYSICAL DISFIGUREMENTS WHICH HAVE WORSENED INTENSELY WITH AGE. HIS SKIN IS GREEN AND SCALY AND HIS BODY HAS GROWN TO GROTESQUE PROPORTIONS. WHILE THESE DISFIGUREMENTS ARE UNQUESTIONABLY THE SOURCES OF JONES' VARIOUS PSYCHOLOGICAL DISORDERS, HIS INTENSE MISANTHROPY SEEMS TO ALSO DERIVE FROM AN UNDERSTANDABLY DIFFICULT CHILDHOOD WHICH INCLUDED ALCOHOLIC RELATIVES AND SOCIAL REJECTION BY HIS PEERS. HE INCREASINGLY EMBRACES AN ANIMALISTIC, SUBHUMAN CONCEPTION OF SELF. ADDITIONAL NOTES: HIS ACUTE MISANTHROPY MAKES HIM DIFFICULT TO TREAT, HE REFUSES TO RESPOND TO SOCIALIZATION, REACTING ONLY WHEN HE IS ACKNOWLEDGED AS A DANGEROUS BEAST, WHICH IS CLEARLY HOW HE VIEWS HIMSELF. IT MAY BE THAT HIS PHYSICAL DISFIGUREMENTS ARE SO SEVERE, HE WILL NEVER BE ABLE TO TRULY INTEGRATE INTO HUMAN SOCIETY. THIS CHALLENGE IS MADE CLEAR BY REPEATED (AND OCCASIONALLY SUCCESSFUL) ATTEMPTS TO MAIM AND KILL THE ASYLUM'S ORDERLIES AND DOCTORS."

notes9 = "ANOTHER SURPRISINGLY INTELLIGENT INMATE. FRIES' NARCISSISM AND ANTISOCIAL DISORDERS ARE SURPASSED ONLY BY HIS INTENSE FIXATION ON HIS LATE WIFE NORA. HIS OBSESSION WITH NORA'S MEMORY HAS DEVELOPED INTO A VARIETY OF PSYCHOPATHIC BEHAVIORS, WORSENED BY HIS NARCISSISTIC EGOMANIA AND LACK OF CONCERN FOR OTHERS. FRIES'S PECULIAR MEDICAL CONDITION - WHICH KEEPS HIS BODY TEMPERATURE BELOW ZERO AND NECESSITATES A VARIETY OF COMPLICATED SECURITY PRECAUTIONS - ONLY FURTHERS HIS ANTISOCIAL TENDENCIES. ADDITIONAL NOTES: YET ANOTHER INMATE HERE AT THE ASYLUM WHO WAS FORMERLY A DOCTOR; CERTAINLY AN ODD PATTERN. TREATMENT IS DIFFICULT DUE TO THE FRIGID TEMPERATURES I AM FORCED TO ENDURE IN HIS PRESENCE."

notes10 = "TRANSFERENCE IS A PROFESSIONAL DANGER THAT EVERY PSYCHIATRIST MUST BE READY FOR, BUT DR. HARLEEN QUINZEL EXPERIENCED WHAT MIGHT BE CLASSIFIED AS DELUSIONAL TRANSFERENCE WHEN SHE CONVINCED HERSELF THAT SHE AND THE JOKER WERE IN LOVE. DISPLAYING SYMPTOMS OF BIPOLAR DISORDER, WITH THE JOKER'S MOOD SWINGS AS THE CAUSATIVE AGENT FOR HER MANIC AND DEPRESSIVE EPISODES, QUINZEL ALSO SHOWS A HIGH LEVEL OF DEPENDENCE ON THE JOKER. HIS MALTREATMENT OF HER GIVES THIS DEPENDENCE A DIMENSION OF SADOMASOCHISM. ADDITIONAL NOTES: SHE SHOWS SIGNS OF EXTREME REGRESSION IN THE JOKER'S PRESENCE. THE EXCESSIVE AND INVASIVE PSYCHOLOGICAL SCREENING I HAD TO UNDERGO HERE AT ARKHAM WAS LARGELY DUE TO HER EARLIER FALL FROM GRACE. AT TIMES I'M RESENTFUL OF THIS; THE MERE IDEA THAT I WOULD BECOME INAPPROPRIATELY INVOLVED WITH THE JOKER OR ANY OTHER INMATE IS PREPOSTEROUS."

# ---------------------------------------------------------------

vigilante1 = Vigilante('BATMAN', 'VIGILANTE')
vigilante_repository.save(vigilante1)

vigilante2 = Vigilante('JAMES GORDEN', 'GCPD')
vigilante_repository.save(vigilante2)

vigilante3 = Vigilante('ROBIN', 'VIGILANTE')
vigilante_repository.save(vigilante3)

vigilante4 = Vigilante('HARVEY BULLOCK', 'GCPD')
vigilante_repository.save(vigilante4)

vigilante5 = Vigilante('BATGIRL', 'VIGILANTE')
vigilante_repository.save(vigilante5)

vigilante6 = Vigilante('RENEE MONTOYA', 'GCPD')
vigilante_repository.save(vigilante6)

vigilante7 = Vigilante('RED HOOD', 'VIGILANTE')
vigilante_repository.save(vigilante7)

vigilante8 = Vigilante('MACKENZIE BOCK', 'GCPD')
vigilante_repository.save(vigilante8)

vigilante9 = Vigilante('HUNTRESS', 'VIGILANTE')
vigilante_repository.save(vigilante9)

vigilante10 = Vigilante('RED ROBIN', 'VIGILANTE')
vigilante_repository.save(vigilante10)

# ---------------------------------------------------------------

doctor1 = Doctor('JOAN LELAND')
doctor_repository.save(doctor1)

doctor2 = Doctor('STEPHEN KELLERMAN')
doctor_repository.save(doctor2)

doctor3 = Doctor('PENELOPE YOUNG')
doctor_repository.save(doctor3)


# ---------------------------------------------------------------

patient1 = Patient('JOKER', 'UNKNOWN', 'UNKNOWN', False, vigilante1, doctor1, notes1)
patient_repository.save(patient1)

patient2 = Patient('SCARECROW', 'JONATHAN CRANE', '33', False, vigilante5, doctor2, notes2)
patient_repository.save(patient2)

patient3 = Patient('THE PENGUIN', 'OSWALD COBBLEPOT', '43', False, vigilante3, doctor3, notes3 )
patient_repository.save(patient3)

patient4 = Patient('THE RIDDLER', 'EDWARD NYGMA', '30', False, vigilante10, doctor1, notes4 )
patient_repository.save(patient4)

patient5 = Patient('POISON IVY', 'PAMELA ISLEY', '38', True, vigilante6, doctor2, notes5 )
patient_repository.save(patient5)

patient6 = Patient('CLAYFACE', 'BASIL KARLO', '39', True, vigilante9, doctor3, notes6 )
patient_repository.save(patient6)

patient7 = Patient('TWO FACE', 'HARVEY DENT', '42', False, vigilante3, doctor1, notes7 )
patient_repository.save(patient7)

patient8 = Patient('KILLER CROC', 'WAYLON JONES', '34', True, vigilante4, doctor2, notes8 )
patient_repository.save(patient8)

patient9 = Patient('MISTER FREEZE', 'VICTOR FRIES', '47', True, vigilante8, doctor3, notes9 )
patient_repository.save(patient9)

patient10 = Patient('HARLEY QUINN', 'HARLEEN QUINZEL', '32', False, vigilante1, doctor1, notes10 )
patient_repository.save(patient10)

# ---------------------------------------------------------------

pdb.set_trace()